### ISSUE TITLE
Questions for Midterm01

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#43]
Hi Professor McGowan,
Here listed some questions I have for review (especially the last one):

1. Can you please explain about "well separated" and why is logistic regression unstable in this situation?
![Explain](https://user-images.githubusercontent.com/59891782/74277165-08f95080-4ce5-11ea-9eec-1daab9283d34.png)

2. Do we need to remember this graph?
![Q2- Do we need to remember](https://user-images.githubusercontent.com/59891782/74277184-11518b80-4ce5-11ea-8d91-aff9f9332ea9.png)

3. Can you please explain which pair of points show the best model/flexibility?
![Q3- How to interpret](https://user-images.githubusercontent.com/59891782/74277310-4bbb2880-4ce5-11ea-97a6-7ee2105e05cf.png)

4. Can you explain why as flexibility increases, bias decreases and variance increases?

5. Do we need to remember these equations? And do the two equations work for the same data, or one for the training data and one for the test data?

6. What does the dashed line mean here? And do we draw the dashed line at the bottom of each curve?
![Q6- How to interpret](https://user-images.githubusercontent.com/59891782/74277565-c421e980-4ce5-11ea-99a8-030bdcc7603f.png)

7. Does the Bayes Classifier mean the Bayes decision boundary, and what is the relationship between these two concepts and the truth?
![Q9- What does it mean](https://user-images.githubusercontent.com/59891782/74277718-09deb200-4ce6-11ea-9c7c-05595e1873cb.png)

8. Will we be tested on the topics below that are not covered in class?
![Q11- Will we be tested](https://user-images.githubusercontent.com/59891782/74277915-55915b80-4ce6-11ea-8e82-37e6a9ae1f61.png)

9. Can you please explain what is the marginal default rate? And why is the dashed StudentYes line is above the dashed StudentNo line while the StudentYes curve is below the StudentNo curve?
![Q12- Explain marginal default rate](https://user-images.githubusercontent.com/59891782/74278071-9ab58d80-4ce6-11ea-9914-a2f75f694a39.png)

10. Will we be tested on the multinomial logistic regression? And can you explain how do we calculate the denominator here, since I do not understand how does L influence the beta values.
![Q13- How to calculate](https://user-images.githubusercontent.com/59891782/74278528-58408080-4ce7-11ea-8966-794857f4dc18.png)

11. What does sensitivity here, just curious.
![Q14- Explain sensitivity](https://user-images.githubusercontent.com/59891782/74278848-da30a980-4ce7-11ea-95b2-356d83485efe.png)

12. I know we use this equation on class, but I just want to make sure that this is the process we use to determine the decision boundary (find X) when K=2, right? What if K>2, is it the same that we equate the three classes?
![Q15- Explain the calculation process](https://user-images.githubusercontent.com/59891782/74278972-08ae8480-4ce8-11ea-9903-94510c1cd3c1.png)

13. How do we explain this plot?
![Q16- Interpret](https://user-images.githubusercontent.com/59891782/74279407-d8b3b100-4ce8-11ea-8e2e-15f9fbbbe162.png)

14. Do we need to know these concepts (i.e. hyperplane etc.)?
![Q17- Do we need to know this](https://user-images.githubusercontent.com/59891782/74279565-216b6a00-4ce9-11ea-8e51-85c61dd051f5.png)

15. Why is it sensible? Is it because we use a different data set to test?
![Q18- Why](https://user-images.githubusercontent.com/59891782/74279745-7dce8980-4ce9-11ea-86f9-122a92f0a17a.png)

16. What does c mean in the equation? If it means class, how can it be multiplied by x? And do we need to know concepts of two learning methods?
![Q18- Will we be tested](https://user-images.githubusercontent.com/59891782/74280931-8031e300-4ceb-11ea-89ca-533d2130b61e.png)

17. Can you please explain again why it biased upward and why does the variance get higher? I am still not clear about the concept of bias-variance trade-off.
![Q21- Def](https://user-images.githubusercontent.com/59891782/74283190-7dd18800-4cef-11ea-96d7-9477a74cb82c.png)

Thank you very much!!!

**Comment by LucyMcGowan** [comment]
Can you please explain about "well separated" and why is logistic regression unstable in this situation?

- well separated means that the predictors separate into the classes VERY well, which sounds like a good thing (and generally is!) but the maximum likelihood estimation procedure has trouble in these cases. The parameter estimates can become infinite

Do we need to remember this graph?
- no

Can you please explain which pair of points show the best model/flexibility?

- the blue points are ideal 

Can you explain why as flexibility increases, bias decreases and variance increases?

- Here is a [blog post](https://towardsdatascience.com/understanding-the-bias-variance-tradeoff-165e6942b229) that tries to explain this

Do we need to remember these equations? And do the two equations work for the same data, or one for the training data and one for the test data?

- which equations?

What does the dashed line mean here? And do we draw the dashed line at the bottom of each curve?

- the vertical dashed line shows the optimal flexibility based on the test error. 
 

Does the Bayes Classifier mean the Bayes decision boundary, and what is the relationship between these two concepts and the truth?

- the Bayes classifier will give the minimum error rate (Assuming the probabilities are known)

Will we be tested on the topics below that are not covered in class?

- no

Can you please explain what is the marginal default rate? And why is the dashed StudentYes line is above the dashed StudentNo line while the StudentYes curve is below the StudentNo curve?

- marginal is the effect without any other variables in the model, the conditional effect is the effect from the model that includes additional variables. The marginal (dashes) effect is different than the conditional curve due to Simpson’s paradox. 

Will we be tested on the multinomial logistic regression? And can you explain how do we calculate the denominator here, since I do not understand how does L influence the beta values.

- you will not be tested on this

What does sensitivity here, just curious.

- sensitivity is another word for true positive rate

I know we use this equation on class, but I just want to make sure that this is the process we use to determine the decision boundary (find X) when K=2, right? What if K>2, is it the same that we equate the three classes?

- yes, except here the priors are equal, that may not always be the case. You won’t have to solve by hand when K > 2

How do we explain this plot?

- this plot helps visualize the data in lower dimensions (that optimally discriminate between groups)

Do we need to know these concepts (i.e. hyperplane etc.)?

- you need to generally understand that LDA is a data reduction method 

Why is it sensible? Is it because we use a different data set to test?

- yes

What does c mean in the equation? If it means class, how can it be multiplied by x? And do we need to know concepts of two learning methods?

- here the cs are constants

Can you please explain again why it biased upward and why does the variance get higher? I am still not clear about the concept of bias-variance trade-off.

- check out the above blog post for bias-variance trade-off 

@skywang0407 I’ve added responses 👍

**Comment by skywang0407** [comment]
Thank you very much!!! I am sorry I ask too much.
