### ISSUE TITLE
Some slide questions before midterm

### ISSUE THREAD

**Issue by Cindyyyhey** [sta-363-s20/community#44]
Dear Professor @LucyMcGowan ,

I have a few questions from slides about the regression part.

1. What does this equation mean? Is that we draw the variance-bias trade off from this equation?
![1](https://user-images.githubusercontent.com/54655629/74304685-c313ab00-4d2b-11ea-84f2-defeb5eaadda.png)

2. I know hat means predicted values, but what does the hat matrix mean here? 
![屏幕快照 2020-02-11 下午9 15 31](https://user-images.githubusercontent.com/54655629/74304883-43d2a700-4d2c-11ea-9115-7a9f4b5bb450.png)

3. I'm so confused about this. What is the sigma here? Is the Var(beta) for calculating the variance of the whole regression model, or just one predictor? Also, I don't understand the formula for SE(beta) here.
![屏幕快照 2020-02-11 下午9 36 09](https://user-images.githubusercontent.com/54655629/74305046-c196b280-4d2c-11ea-88a2-b1798d30ec55.png)

4. For assessing a model, why do we use RSE instead of RSS(since we always calculate RSS for a test dataset to test the model )? What is the difference between RSE and RSS?
![屏幕快照 2020-02-11 下午10 06 36](https://user-images.githubusercontent.com/54655629/74305171-23571c80-4d2d-11ea-8b2d-3c825078f8b0.png)

5. What does the summarise(reduce variables to values) mean here?
![屏幕快照 2020-02-11 下午11 28 28](https://user-images.githubusercontent.com/54655629/74305272-74671080-4d2d-11ea-89ac-9c1d87caf0f0.png)
 
6. Do we need to memorize or understand these two complicated formulas? 
![屏幕快照 2020-02-11 下午11 33 22](https://user-images.githubusercontent.com/54655629/74305295-88ab0d80-4d2d-11ea-9348-1426848db3ec.png)
![屏幕快照 2020-02-11 下午10 59 10](https://user-images.githubusercontent.com/54655629/74305298-8c3e9480-4d2d-11ea-9c51-2a90346fd972.png)

7. Why false positive rate keep decreasing and false negative keep increasing? Is this tendency for all lda models? What does the x-axis threshold mean here? 
![屏幕快照 2020-02-11 下午11 50 40](https://user-images.githubusercontent.com/54655629/74305347-a5dfdc00-4d2d-11ea-8f57-597b410d0e9c.png)

8. The last one!! What does the area under ROC curve mean? Which one is better, higher or lower AUC? (I think low auc is better because both false rates are low.)
![屏幕快照 2020-02-11 下午11 51 03](https://user-images.githubusercontent.com/54655629/74305471-03742880-4d2e-11ea-9a81-9afcf170a129.png)

Thanks a lot!!!

**Comment by LucyMcGowan** [comment]
What does this equation mean? Is that we draw the variance-bias trade off from this equation?

- Yes

I know hat means predicted values, but what does the hat matrix mean here?

- It’s the matrix that you multiply y by to turn y into y hat

I'm so confused about this. What is the sigma here? Is the Var(beta) for calculating the variance of the whole regression model, or just one predictor? Also, I don't understand the formula for SE(beta) here.

- sigma is the variance of the error term var(beta) is for just the beta coefficient(s) SE(beta) is the square root of the variance - the standard error. 

For assessing a model, why do we use RSE instead of RSS(since we always calculate RSS for a test dataset to test the model )? What is the difference between RSE and RSS?

- RSE is a function of RSS - it accounts for the sample size and the number of predictors

What does the summarise(reduce variables to values) mean here?

- the summarize function is used to summarize across multiple observations (for example to take the mean with groups specified by a group_by function)

Do we need to memorize or understand these two complicated formulas?

- no

Why false positive rate keep decreasing and false negative keep increasing? Is this tendency for all lda models? What does the x-axis threshold mean here?

- this is specific to the Credit Default model - the x-axis is the threshold chosen to determine which group to classify a new observation into (it’s specified on the previous slide)

The last one!! What does the area under ROC curve mean? Which one is better, higher or lower AUC? (I think low auc is better because both false rates are low.)

- AUC is the area under the ROC curve. Larger is better - here is a [blog post](https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5) with more details

**Comment by Cindyyyhey** [comment]
Thanks a lot!!!!!!
