### ISSUE TITLE
Questions for Midterm 2

### ISSUE THREAD

**Issue by skywang0407** [sta-363-s20/community#68]
Hi Lucy,
I want to ask you some questions:

1. Do I understand it right: when =0, linear regression; when goes to infinity, it goes down?
![#1 Is this correct when =0, linear; infininty, goes down](https://user-images.githubusercontent.com/59891782/77808625-7f1e0080-7062-11ea-80e0-09ae21b6495c.png)

2. Do we need to standardize variables ourselves in exam?
![#2 Do we need to standardize variables ourselves in exam](https://user-images.githubusercontent.com/59891782/77808633-8b09c280-7062-11ea-95e6-ad45dab11c76.png)

3. Is it estimating training error?
![#3](https://user-images.githubusercontent.com/59891782/77808651-9bba3880-7062-11ea-9f08-65f89eccfad5.png)

4. Can you explain "scale the variables" again? Is it because we want all the betas on the same scale to be comparable? And what will happen if we scale before doing CV?
![#4 receipe](https://user-images.githubusercontent.com/59891782/77808696-d6bc6c00-7062-11ea-8f24-76cfc9510432.png)

5. For the step functions,  does it mean for X <35, 35<X<65, X>65, their related Y values are the same on the straight line of Y=# ?
![#5 For the steps does it mean for X smaller 35 their Y values are the same on the straight line](https://user-images.githubusercontent.com/59891782/77808802-429ed480-7063-11ea-8636-02d77fec71ae.png)

Thanks!

**Comment by skywang0407** [comment]
Q3 is Page 17 in Slides tidymodels.

**Comment by mohammad-r-k** [comment]
1. When Lambda goes to infinity, each term which have lambda becomes very big, but since this terms are inverted in this equation, they become very small (near to zero) and by multiplying these terms to other terms, make the whole equation equal to zero, so variance become zero.

2) I don't know if we have to compute it in exam or not, but all you have to do is to divide the variables by the standard deviation.

3) I think it estimating training root mean square error.

4) 
a) Since we apply same Lambda to each beta coefficient (we use same penalty term for all betas), we want all the beta values have the same scale, so we want X to be scaled by the standard deviation, so the beta can be comparable.

b) No, they are not the same, we should scale after cross validation.
For scaling, we should divide by SD of each fold.

5. Yes, for each specified interval of X, Y's are the same!

**Comment by LucyMcGowan** [comment]
Thank you @mohammad-r-k! I agree with all of the above, if you had to scale a variable on the exam I would provide the standard deviation.

**Comment by tkinsella333** [comment]
@LucyMcGowan you would need to subtract the mean and then divide by the SD right?

**Comment by tkinsella333** [comment]
nevermind, just dividing by the SD is sufficient. (and I believe subtracting by the mean and then dividing can at least be ok in cases where we assume the variable is Gaussian? or this works possibly in all cases as well? )

**Comment by LucyMcGowan** [comment]
@tkinsella333 yep! you just need to scale, centering is fine, it doesn’t hurt but not necessary

**Comment by skywang0407** [comment]
Got it, thank you all!
